### PR TITLE
Add README_zh-cn.md

### PR DESCRIPTION
**Pull request by Too-Naive**
- Add link to README.md(Simplified Chinese)
- ~~Deleted or modified some row follow: https://www.quora.com/Why-are-Chinese-people-always-apologising-for-their-poor-English~~

### CODE REVIEW

**Comment by vfleaking** [comment]
There is no need to remove this line in README.
Actually I just want to say there is no more English documents, not to apologize.
I think our users will feel uncomfortable reading English documentation, haha. This is the real reason why only the README file is written in English.

**Comment by Too-Naive** [comment]
check

**Comment by Too-Naive** [comment]
Please review again, Thanks.

**Comment by vfleaking** [comment]
感觉好翻译腔。。 0.0

**Comment by Too-Naive** [comment]
总是可以修改的嘛...........如果无人看过这个翻译的话 永远都不会有改进的

**Pull request closed without merging**
